### ISSUE TITLE
Wiki/Readme creation

### ISSUE THREAD

**Issue by John-H-Smith** [gruppe-adler/grad_prism#3]
Hey there,
could you please create a wiki or at least a readme on how to install/use the exporter?
That would be great, thanks in advance!

**Comment by DerZade** [comment]
Hey there!

Thanks for taking hinterst in our project. To be honest I'm not sure how much WIP this still ist. The basics should theoretically work, but understand that this is not a "finished" project.
Therefore the available metrics are the format of those may change in the future and that's also the reason why there is no README or wiki.

Installation should be quite easy tho. Just start the mod (+ [Intercept](https://steamcommunity.com/sharedfiles/filedetails/?id=1645973522)) on the server. The Prometheus endpoint should be available on Server-Port + 5 (i.e. Server Port 2302 -> Prometheus Port 2307).

**Comment by John-H-Smith** [comment]
Alright, thank you!
How do get the mod files? Do I have to compile anything by myself? If yes, how do I do that?
Thanks in advance.

**Comment by DerZade** [comment]
Ouf I didn't notice, that there was no release...

We have a GitHub-Action that builds the mod for Linux and Windows and uploads them as artifacts ([see here](https://github.com/gruppe-adler/grad_prism/actions/runs/2391665115#artifacts)).

These are the builds for the latest commit:
- [Linux](https://github.com/gruppe-adler/grad_prism/files/9207822/grad_prism_ubuntu.zip)
- [Windows](https://github.com/gruppe-adler/grad_prism/files/9207821/grad_prism_windows.zip)

**Comment by John-H-Smith** [comment]
Alright, I will test it.
As soon I get it working I come back and will create a pull request for a readme.

**Comment by John-H-Smith** [comment]
Sorry to bother you again.
I just tried to access the data exposed on port 2307, but there is none even if the plugin is loaded:

```
root@root1 /home/arma/server # grep prism latest_errors.log
12:41:27 /home/arma/server/mods/@grad_prism/addons/grad_prism_main.pbo - unknown
12:41:27                                        @grad_prism |          @grad_prism |      false |      false |             GAME DIR | hash-censored |  censored | /home/arma/server/mods/@grad_prism
12:41:28 Intercept Loading Plugin: grad_prism
```

```
root@root1 /home/arma/server # grep 2307 latest_errors.log | wc -l
0
```

```
root@root1 /home/arma/server # netstat -telpn | grep 2307 | wc -l
0
```

Maybe that could result on an issue with intercept:
```12:41:28 Initializing Intercept
CallExtension 'intercept' could not be found
12:41:28 Intercept initialization part 1/3: 
CallExtension 'intercept' could not be found
CallExtension 'intercept' could not be found
12:41:28 Error in expression <interceptRegisterTypes parsingNamespace>
12:41:28   Error position: <parsingNamespace>
12:41:28   Error Missing ;
12:41:28 Error in expression <interceptRegisterTypes parsingNamespace>
12:41:28   Error position: <parsingNamespace>
12:41:28   Error Missing ;
12:41:28 Intercept initialization part 2/3: any
12:41:28 Intercept Loading Plugin: grad_prism
CallExtension 'intercept' could not be found
CallExtension 'intercept' could not be found
12:41:28 Intercept initialization part 3/3: 
```
Any ideas?

**Comment by TheWillard** [comment]
Do you have BattlEye enabled? If so, could you disable it and try again?

**Comment by John-H-Smith** [comment]
> Do you have BattlEye enabled? If so, could you disable it and try again?

I just checked with disabled BattlEye, but there is still no port 2307 in usage.

**Comment by TheWillard** [comment]
I just realized that you're using Linux, there is a bunch of stuff missing for Linux. But it should still work on the "default" port 1342. Could you check if it's in usage? It should also print the used port in the rpt.

**Comment by John-H-Smith** [comment]
> I just realized that you're using Linux, there is a bunch of stuff missing for Linux. But it should still work on the "default" port 1342. Could you check if it's in usage? It should also print the used port in the rpt.

Alright, but there's still nothing:
```
root@root1 ~ # netstat -telpn | grep 1342 | wc -l
0
root@root1 ~ # grep 1342 /home/arma/server/latest_errors.log | wc -l
0
```

**Comment by TheWillard** [comment]
So I tested it myself and apparently there only exists an 32bit Arma Server for Linux and vcpkg only supports 64bit builds for Linux out of the box.

**Comment by John-H-Smith** [comment]
> So I tested it myself and apparently there only exists an 32bit Arma Server for Linux and vcpkg only supports 64bit builds for Linux out of the box.

Thanks for testing!
Actually, there's a 64-bit version of Arma 3 Server! 
Just download the server's files and you will find a file called `arma3server_x64`. It's running fine as server binary for my own server.
My os is also running on 64-bit.

**Comment by TheWillard** [comment]
Good catch! Apparently I'm blind.... Unfortunately there is no 64 bit Version of Intercept for Linux (https://github.com/intercept/intercept/pull/262)
